from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List

from .image_ops import FilterParams


@dataclass(frozen=True)
class FilterPreset:
    name: str
    params: FilterParams
    category: str = "General"
    source_path: str | None = None


def presets() -> List[FilterPreset]:
    # Values are tuned to be “creative” rather than physically accurate.
    items = [
        FilterPreset("None", FilterParams(), category="General"),
        FilterPreset(
            "Punchy",
            FilterParams(contrast=0.22, saturation=0.18, vibrance=0.15, levels_black=0.02, levels_white=0.98),
            category="General",
        ),
        FilterPreset(
            "Soft",
            FilterParams(contrast=-0.12, brightness=0.02, saturation=-0.05, curve_points=((0.0, 0.03), (0.5, 0.55), (1.0, 0.98))),
            category="General",
        ),
        FilterPreset(
            "Matte",
            FilterParams(
                contrast=-0.05,
                saturation=-0.06,
                levels_black=0.03,
                levels_white=0.97,
                curve_points=((0.0, 0.08), (0.35, 0.35), (0.75, 0.78), (1.0, 0.98)),
            ),
            category="General",
        ),
        FilterPreset(
            "Fade",
            FilterParams(contrast=-0.18, brightness=0.03, saturation=-0.12, curve_points=((0.0, 0.10), (0.6, 0.62), (1.0, 0.95))),
            category="General",
        ),
        FilterPreset(
            "Warm",
            FilterParams(channel_mul=(1.06, 1.0, 0.94), saturation=0.08, contrast=0.06),
            category="General",
        ),
        FilterPreset(
            "Cool",
            FilterParams(channel_mul=(0.95, 1.0, 1.07), saturation=0.06, contrast=0.05),
            category="General",
        ),
        FilterPreset(
            "Golden Hour",
            FilterParams(channel_mul=(1.10, 1.02, 0.90), brightness=0.02, contrast=0.08, vibrance=0.10),
            category="General",
        ),
        FilterPreset(
            "Teal & Orange",
            FilterParams(
                saturation=0.10,
                contrast=0.16,
                split_shadows=(0.00, 0.08, 0.10),
                split_highlights=(0.10, 0.05, 0.00),
                split_balance=-0.10,
                split_amount=0.45,
                levels_black=0.02,
                levels_white=0.98,
            ),
            category="General",
        ),
        FilterPreset(
            "Cinematic",
            FilterParams(
                contrast=0.12,
                saturation=-0.04,
                vibrance=0.12,
                split_shadows=(0.00, 0.06, 0.10),
                split_highlights=(0.08, 0.04, 0.00),
                split_amount=0.30,
                curve_points=((0.0, 0.02), (0.25, 0.22), (0.75, 0.82), (1.0, 0.98)),
            ),
            category="General",
        ),
        FilterPreset(
            "Bleach Bypass",
            FilterParams(contrast=0.22, saturation=-0.45, levels_black=0.01, levels_white=0.99, curve_points=((0.0, 0.0), (0.5, 0.56), (1.0, 1.0))),
            category="Film / Chemical",
        ),
        FilterPreset(
            "Sepia",
            FilterParams(channel_mul=(1.08, 1.02, 0.86), saturation=-0.10, contrast=0.05, split_highlights=(0.08, 0.04, 0.00), split_amount=0.20),
            category="Film / Chemical",
        ),
        FilterPreset(
            "Vintage",
            FilterParams(
                contrast=-0.08,
                saturation=-0.15,
                channel_mul=(1.06, 1.0, 0.92),
                curve_points=((0.0, 0.10), (0.4, 0.38), (0.85, 0.86), (1.0, 0.96)),
            ),
            category="Film / Chemical",
        ),
        FilterPreset(
            "Cross Process",
            FilterParams(
                contrast=0.12,
                saturation=0.12,
                hue_degrees=6.0,
                split_shadows=(0.00, 0.05, 0.10),
                split_highlights=(0.10, 0.06, 0.00),
                split_amount=0.25,
                levels_gamma=0.92,
            ),
            category="Film / Chemical",
        ),
        FilterPreset(
            "Cross Process (Green)",
            FilterParams(
                contrast=0.14,
                saturation=0.14,
                hue_degrees=-10.0,
                channel_mul=(0.96, 1.06, 0.98),
                split_shadows=(0.00, 0.10, 0.06),
                split_highlights=(0.08, 0.10, 0.00),
                split_balance=-0.08,
                split_amount=0.35,
                levels_black=0.02,
                levels_white=0.98,
                levels_gamma=0.90,
            ),
            category="Film / Chemical",
        ),
        FilterPreset(
            "Cross Process (Purple)",
            FilterParams(
                contrast=0.12,
                saturation=0.16,
                hue_degrees=14.0,
                channel_mul=(1.04, 0.96, 1.06),
                split_shadows=(0.06, 0.00, 0.12),
                split_highlights=(0.10, 0.06, 0.00),
                split_balance=-0.10,
                split_amount=0.35,
                curve_points=((0.0, 0.04), (0.35, 0.32), (0.75, 0.86), (1.0, 0.98)),
            ),
            category="Film / Chemical",
        ),
        FilterPreset(
            "Slide Pop",
            FilterParams(
                contrast=0.22,
                saturation=0.20,
                vibrance=0.18,
                levels_black=0.01,
                levels_white=0.99,
                levels_gamma=0.92,
                curve_points=((0.0, 0.0), (0.25, 0.16), (0.75, 0.88), (1.0, 1.0)),
                channel_mul=(1.03, 1.00, 0.98),
            ),
            category="Film / Chemical",
        ),
        FilterPreset(
            "Expired Print",
            FilterParams(
                contrast=-0.10,
                saturation=-0.18,
                vibrance=0.10,
                levels_black=0.04,
                levels_white=0.96,
                levels_gamma=0.95,
                channel_mul=(1.05, 1.00, 0.92),
                split_shadows=(0.04, 0.00, 0.08),
                split_highlights=(0.10, 0.06, 0.00),
                split_balance=-0.10,
                split_amount=0.25,
                curve_points=((0.0, 0.10), (0.4, 0.38), (0.85, 0.88), (1.0, 0.97)),
            ),
            category="Film / Chemical",
        ),
        FilterPreset(
            "Kodachrome-ish",
            FilterParams(
                contrast=0.18,
                saturation=0.10,
                vibrance=0.18,
                channel_mul=(1.06, 1.00, 0.94),
                levels_black=0.02,
                levels_white=0.98,
                curve_points=((0.0, 0.02), (0.25, 0.18), (0.75, 0.86), (1.0, 0.98)),
            ),
            category="Film / Chemical",
        ),
        FilterPreset(
            "Lo-Fi Warm",
            FilterParams(
                contrast=-0.12,
                brightness=0.03,
                saturation=0.16,
                vibrance=0.18,
                channel_mul=(1.10, 1.00, 0.90),
                levels_black=0.06,
                levels_white=0.98,
                curve_points=((0.0, 0.16), (0.35, 0.40), (0.8, 0.86), (1.0, 0.98)),
            ),
            category="Lo-Fi",
        ),
        FilterPreset(
            "Lo-Fi Cool",
            FilterParams(
                contrast=-0.10,
                brightness=0.02,
                saturation=0.14,
                vibrance=0.20,
                channel_mul=(0.92, 1.00, 1.12),
                levels_black=0.06,
                levels_white=0.98,
                curve_points=((0.0, 0.16), (0.35, 0.40), (0.8, 0.86), (1.0, 0.98)),
            ),
            category="Lo-Fi",
        ),
        FilterPreset(
            "Disposable Camera",
            FilterParams(
                contrast=-0.06,
                brightness=0.02,
                saturation=0.10,
                vibrance=0.10,
                levels_black=0.05,
                levels_white=0.95,
                levels_gamma=0.96,
                channel_mul=(1.06, 1.00, 0.92),
                split_highlights=(0.10, 0.06, 0.00),
                split_amount=0.20,
            ),
            category="Lo-Fi",
        ),
        FilterPreset(
            "90s Flash",
            FilterParams(
                contrast=0.08,
                brightness=0.04,
                saturation=0.18,
                vibrance=0.18,
                levels_black=0.04,
                levels_white=0.96,
                channel_mul=(1.08, 1.00, 0.94),
                curve_points=((0.0, 0.10), (0.5, 0.58), (1.0, 0.98)),
            ),
            category="Lo-Fi",
        ),
        FilterPreset(
            "Candy Color",
            FilterParams(
                hue_degrees=12.0,
                contrast=0.10,
                saturation=0.30,
                vibrance=0.30,
                levels_black=0.03,
                levels_white=0.98,
                levels_gamma=0.94,
            ),
            category="Lo-Fi",
        ),
        FilterPreset(
            "High Key",
            FilterParams(brightness=0.07, contrast=-0.05, levels_black=0.02, levels_white=0.95, saturation=-0.04),
            category="General",
        ),
        FilterPreset(
            "Low Key",
            FilterParams(exposure=-0.35, contrast=0.18, saturation=-0.05, levels_black=0.01, levels_white=0.98),
            category="General",
        ),
        FilterPreset(
            "B&W Classic",
            FilterParams(saturation=-1.0, contrast=0.18, levels_black=0.01, levels_white=0.99, curve_points=((0.0, 0.0), (0.35, 0.30), (0.75, 0.82), (1.0, 1.0))),
            category="Black & White",
        ),
        FilterPreset(
            "B&W Soft",
            FilterParams(saturation=-1.0, contrast=-0.05, brightness=0.03, levels_black=0.02, levels_white=0.98, curve_points=((0.0, 0.05), (0.5, 0.55), (1.0, 0.98))),
            category="Black & White",
        ),
        FilterPreset(
            "B&W Dramatic",
            FilterParams(saturation=-1.0, contrast=0.32, levels_black=0.02, levels_white=0.98, curve_points=((0.0, 0.0), (0.2, 0.12), (0.8, 0.90), (1.0, 1.0))),
            category="Black & White",
        ),
        FilterPreset(
            "Muted Greens",
            FilterParams(hue_degrees=4.0, saturation=-0.10, vibrance=0.06, channel_mul=(1.0, 1.02, 0.98), contrast=0.06),
            category="General",
        ),
        FilterPreset(
            "Rose",
            FilterParams(channel_mul=(1.05, 0.98, 1.03), saturation=0.08, split_highlights=(0.10, 0.00, 0.06), split_amount=0.18),
            category="General",
        ),
        FilterPreset(
            "Lavender",
            FilterParams(hue_degrees=10.0, saturation=0.05, channel_mul=(1.0, 0.98, 1.06), contrast=0.06),
            category="General",
        ),
        FilterPreset(
            "Emerald",
            FilterParams(hue_degrees=-8.0, saturation=0.12, channel_mul=(0.96, 1.06, 0.98), contrast=0.08),
            category="General",
        ),
        FilterPreset(
            "Polarizer (approx)",
            FilterParams(contrast=0.14, saturation=0.18, vibrance=0.25, levels_black=0.02, levels_white=0.98),
            category="General",
        ),
        FilterPreset(
            "Clarity (approx)",
            FilterParams(contrast=0.20, levels_black=0.01, levels_white=0.99, levels_gamma=0.95, saturation=0.05),
            category="General",
        ),
        FilterPreset(
            "Flat Log-ish",
            FilterParams(contrast=-0.25, levels_black=0.02, levels_white=0.98, curve_points=((0.0, 0.05), (0.5, 0.50), (1.0, 0.95))),
            category="General",
        ),
        FilterPreset(
            "Film Print",
            FilterParams(contrast=0.14, saturation=0.06, curve_points=((0.0, 0.02), (0.25, 0.20), (0.7, 0.78), (1.0, 0.98)), channel_mul=(1.02, 1.00, 0.98)),
            category="Film / Chemical",
        ),
        FilterPreset(
            "Night",
            FilterParams(exposure=-0.20, channel_mul=(0.92, 0.98, 1.08), saturation=-0.05, contrast=0.10),
            category="General",
        ),
        FilterPreset(
            "Sun Kissed",
            FilterParams(channel_mul=(1.08, 1.01, 0.94), saturation=0.12, vibrance=0.10, brightness=0.01, contrast=0.08),
            category="General",
        ),
        FilterPreset(
            "Deep Shadows",
            FilterParams(contrast=0.20, levels_black=0.03, levels_white=0.99, levels_gamma=0.92, saturation=0.02),
            category="General",
        ),
        FilterPreset(
            "Pastel",
            FilterParams(contrast=-0.10, saturation=-0.02, vibrance=0.18, brightness=0.03, curve_points=((0.0, 0.08), (0.55, 0.60), (1.0, 0.98))),
            category="General",
        ),
        FilterPreset(
            "Infrared-ish",
            FilterParams(hue_degrees=28.0, saturation=0.30, contrast=0.10, channel_mul=(1.05, 0.98, 0.98)),
            category="Wild",
        ),

        # --- Wild / unconventional looks ---
        FilterPreset(
            "Vaporwave",
            FilterParams(
                hue_degrees=18.0,
                saturation=0.28,
                vibrance=0.25,
                contrast=0.10,
                channel_mul=(1.08, 0.98, 1.10),
                split_shadows=(0.10, 0.00, 0.12),
                split_highlights=(0.00, 0.10, 0.12),
                split_balance=-0.05,
                split_amount=0.35,
                curve_points=((0.0, 0.06), (0.35, 0.33), (0.75, 0.84), (1.0, 0.98)),
            ),
            category="Wild",
        ),
        FilterPreset(
            "Acid Pop",
            FilterParams(
                hue_degrees=42.0,
                saturation=0.45,
                vibrance=0.40,
                contrast=0.20,
                levels_black=0.01,
                levels_white=0.99,
                levels_gamma=0.92,
                curve_points=((0.0, 0.02), (0.25, 0.18), (0.65, 0.84), (1.0, 0.98)),
            ),
            category="Wild",
        ),
        FilterPreset(
            "Neon Nights",
            FilterParams(
                exposure=-0.10,
                contrast=0.24,
                saturation=0.20,
                vibrance=0.45,
                channel_mul=(0.92, 1.02, 1.16),
                split_shadows=(0.00, 0.10, 0.16),
                split_highlights=(0.14, 0.02, 0.10),
                split_balance=-0.15,
                split_amount=0.55,
                levels_black=0.02,
                levels_white=0.98,
            ),
            category="Wild",
        ),
        FilterPreset(
            "Toxic Green",
            FilterParams(
                hue_degrees=-22.0,
                saturation=0.35,
                vibrance=0.30,
                contrast=0.14,
                channel_mul=(0.92, 1.18, 0.92),
                split_shadows=(0.00, 0.12, 0.00),
                split_highlights=(0.05, 0.12, 0.00),
                split_amount=0.40,
                curve_points=((0.0, 0.03), (0.35, 0.28), (0.8, 0.92), (1.0, 0.99)),
            ),
            category="Wild",
        ),
        FilterPreset(
            "Cyanotype (approx)",
            FilterParams(
                saturation=-0.35,
                contrast=0.10,
                channel_mul=(0.85, 1.00, 1.25),
                split_shadows=(0.00, 0.05, 0.16),
                split_highlights=(0.00, 0.10, 0.20),
                split_balance=-0.05,
                split_amount=0.55,
                levels_black=0.02,
                levels_white=0.98,
                curve_points=((0.0, 0.02), (0.3, 0.18), (0.7, 0.82), (1.0, 0.98)),
            ),
            category="Wild",
        ),
        FilterPreset(
            "Redscale (approx)",
            FilterParams(
                hue_degrees=8.0,
                saturation=0.10,
                contrast=0.12,
                channel_mul=(1.25, 0.92, 0.80),
                split_shadows=(0.18, 0.03, 0.00),
                split_highlights=(0.20, 0.08, 0.00),
                split_balance=-0.10,
                split_amount=0.45,
                levels_black=0.02,
                levels_white=0.97,
                curve_points=((0.0, 0.08), (0.4, 0.36), (0.8, 0.88), (1.0, 0.98)),
            ),
            category="Wild",
        ),
        FilterPreset(
            "Magenta Crush",
            FilterParams(
                hue_degrees=30.0,
                saturation=0.35,
                vibrance=0.25,
                contrast=0.12,
                channel_mul=(1.12, 0.92, 1.18),
                split_shadows=(0.12, 0.00, 0.10),
                split_highlights=(0.10, 0.00, 0.14),
                split_amount=0.38,
                levels_gamma=0.95,
            ),
            category="Wild",
        ),
        FilterPreset(
            "Alien Skin",
            FilterParams(
                hue_degrees=-55.0,
                saturation=0.30,
                vibrance=0.20,
                contrast=0.10,
                channel_mul=(0.90, 1.12, 1.00),
                split_shadows=(0.00, 0.12, 0.08),
                split_highlights=(0.08, 0.00, 0.10),
                split_balance=-0.05,
                split_amount=0.45,
            ),
            category="Wild",
        ),
        FilterPreset(
            "Solar Flare",
            FilterParams(
                exposure=0.10,
                contrast=0.22,
                saturation=0.22,
                vibrance=0.22,
                channel_mul=(1.18, 1.02, 0.82),
                split_shadows=(0.06, 0.00, 0.10),
                split_highlights=(0.22, 0.10, 0.00),
                split_balance=0.05,
                split_amount=0.60,
                levels_black=0.01,
                levels_white=0.98,
                curve_points=((0.0, 0.0), (0.25, 0.16), (0.8, 0.92), (1.0, 1.0)),
            ),
            category="Wild",
        ),
        FilterPreset(
            "Deep Purple Shadows",
            FilterParams(
                contrast=0.14,
                saturation=0.12,
                channel_mul=(1.04, 0.96, 1.10),
                split_shadows=(0.10, 0.00, 0.16),
                split_highlights=(0.04, 0.02, 0.00),
                split_balance=-0.20,
                split_amount=0.55,
                levels_gamma=0.92,
            ),
            category="Wild",
        ),
        FilterPreset(
            "Ice Fire",
            FilterParams(
                contrast=0.18,
                vibrance=0.20,
                saturation=0.10,
                split_shadows=(0.00, 0.10, 0.20),
                split_highlights=(0.22, 0.10, 0.00),
                split_balance=0.00,
                split_amount=0.70,
                levels_black=0.02,
                levels_white=0.98,
            ),
            category="Wild",
        ),
        FilterPreset(
            "Color Invert-ish",
            FilterParams(
                # Approximate “inversion” vibe via aggressive hue rotation + lifted blacks + strong curve.
                hue_degrees=180.0,
                saturation=0.20,
                contrast=-0.08,
                levels_black=0.06,
                levels_white=0.98,
                curve_points=((0.0, 0.18), (0.35, 0.55), (0.7, 0.80), (1.0, 0.98)),
                split_shadows=(0.06, 0.10, 0.00),
                split_highlights=(0.00, 0.08, 0.12),
                split_amount=0.40,
            ),
            category="Wild",
        ),
    ]

    pilgram_names = [
        "aden",
        "amaro",
        "ashby",
        "brannan",
        "brooklyn",
        "charmes",
        "clarendon",
        "crema",
        "dogpatch",
        "earlybird",
        "gingham",
        "ginza",
        "hefe",
        "helena",
        "hudson",
        "inkwell",
        "juno",
        "kelvin",
        "lark",
        "lofi",
        "ludwig",
        "maven",
        "mayfair",
        "moon",
        "nashville",
        "perpetua",
        "poprocket",
        "reyes",
        "rise",
        "sierra",
        "skyline",
        "slumber",
        "stinson",
        "sutro",
        "toaster",
        "valencia",
        "walden",
        "willow",
        "xpro2",
    ]
    items.extend(
        FilterPreset(
            name=f"IG: {name.title()}",
            params=FilterParams(pilgram_filter=name),
            category="Instagram",
        )
        for name in pilgram_names
    )

    return items


def preset_map() -> Dict[str, FilterPreset]:
    items = presets()
    return {p.name: p for p in items}
